name: BrowserCat
options:
  bundleIdPrefix: ua.com.rmarinsky
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: 1.0.0
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.0

configs:
  Debug: debug
  Release: release

settings:
  base:
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "2"
    DEVELOPMENT_TEAM: "8JL9TM5WLG"
    CODE_SIGN_STYLE: Automatic
    ARCHS: "arm64 x86_64"
    ENABLE_HARDENED_RUNTIME: YES
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
    Release:
      ONLY_ACTIVE_ARCH: NO

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

targets:
  BrowserCat:
    type: application
    platform: macOS
    sources:
      - path: BrowserCat
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: LaunchAtLogin
      - package: Pow
    settings:
      base:
        INFOPLIST_FILE: BrowserCat/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: BrowserCat/Resources/BrowserCat.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
      configs:
        Debug:
          PRODUCT_NAME: "BrowserCat DEV"
          PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.browsercat.dev
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV_BUILD DEBUG
        Release:
          PRODUCT_NAME: "BrowserCat"
          PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.browsercat

schemes:
  BrowserCat DEV:
    build:
      targets:
        BrowserCat: all
    run:
      config: Debug
    archive:
      config: Debug

  BrowserCat:
    build:
      targets:
        BrowserCat: all
    run:
      config: Release
    archive:
      config: Release
